config/routes.rb
Rails.application.routes.draw do

  get       'sessions/new'

  root	    'static_pages#home'
  
  get       'nda_page'        =>  'users#nda_page'
  
  get       'signup_1'        =>  'users#new'
  
  post      'signup_2'        =>  'users#create'
  
  patch     'new_user_feed'	  =>  'users#augment'
  
  get       'feed'            =>  'users#index'
  
  get       'review'          =>  'users#review'

  get       'login'           => 'sessions#new'
  post      'login'           => 'sessions#create'
  
  delete    'logout'          => 'sessions#destroy'

  resources :users
  resources :recommendations

end

app/models/book.rb
class Book < ActiveRecord::Base
  
  #Commented out for testing the fields_for method
  has_and_belongs_to_many :users
  #has_many :books_users
  #has_many :users, :through => :books_users
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :category, presence: true
  validates :description, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/things_to_read.rb
class ThingsToRead < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recommendations, dependent: :destroy
  #Commented out to test fields_for
  has_and_belongs_to_many :books
  #has_many :books_users
  #has_many :books, :through => :books_users
  has_and_belongs_to_many :movies
  has_and_belongs_to_many :songs
  has_and_belongs_to_many :games
  has_and_belongs_to_many :foods
  has_and_belongs_to_many :destinations
  accepts_nested_attributes_for :books
  accepts_nested_attributes_for :movies
  accepts_nested_attributes_for :songs
  accepts_nested_attributes_for :games
  accepts_nested_attributes_for :foods
  accepts_nested_attributes_for :destinations

  before_save {self.username = username.downcase}
  before_save {self.email    = email.downcase}

  # Username is required and must be unique; not case sensitive
  validates :username, presence: true, uniqueness: {case_sensitive: false}, 
                       length: {maximum: 30} 
  # First and last name are required; maximum of 20 characters
  validates :firstName, presence: true, length: {maximum: 20}
  validates :lastName, presence: true, length: {maximum: 20}
  validates :birthday, presence: true
  # Password is required; still needs to be encrypted
  validates :password_digest, presence: true, length: {minimum: 8}

  # Email address is required and must be unique; not case sensitive; must follow correct format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
                    format: {with: VALID_EMAIL_REGEX }, 
                    uniqueness: {case_sensitive: false}

  has_secure_password
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
    @users = User.all
  end

  private
    def book_params
      params.require(:book).permit(:title, :user_ids => [])
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    # uses the user_id that's passed to find a user and create a recommendation for that user
    @temp_id = recommendation_params["user_id"]
    @user = User.find(@temp_id)
    @recommendation = @user.recommendations.build(recommendation_params)
    if @recommendation.save
      flash[:success] = "Recommendation submitted!"
      # maybe this should redirect to @user
      redirect_to feed_url
    else
      redirect_to :back
    end
  end

  def destroy
  end

  # this action gets called when a user is reviewing recommendations
  # once the change is made, the success message is shown and they are redirected to the review page
  def update
    @user = current_user
    @recommendation = Recommendation.find(params[:id])
    if @recommendation.update_attributes(recommendation_params)
      flash[:success] = "Recommendation feedback accepted"
      redirect_to :back
    else
      redirect_to :back
    end  
  end

  def show
    @recommendation = Recommendation.find(params[:id])  
    @user = current_user

    # add javascript template to allow recommendation to be shown in pop up window
    respond_to do |format|
      format.js 
      format.html 
    end
  end

  private
  
    def recommendation_params
      params.require(:recommendation).permit(:title, :category, :description, :user_id, :feedback)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/nda_page_helper.rb
module NdaPageHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  #Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirects to stored Location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  #Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def age(id)
    @now = Date.today
    @user = User.find(id)
     if @user.birthday.month < @now.month
       @user_age = @now.year - @user.birthday.year
         #print @user_age
     elsif @user.birthday.month == @now.month
       if @user.birthday.day <= @now.day
         @user_age = @now.year - @user.birthday.year
         #print @user_age
       end
     else
         @user_age = @now.year - @user.birthday.year - 1
         #print @user_age
     end

    #puts "here!"
  end
end

app/views/recommendations/_feedback.html.erb
<div>
  <!-- TODO: replace :category with :feedback -->
  <%= form_for(@recommendation) do |f| %>
    <%= f.label :category, "What do you think of this recommendation?" %><br><br>
    <%= f.radio_button(:category, "1") %>
    <%= f.label(:yes, "This is definitely for me.") %><br>
    <%= f.radio_button(:category, ".5") %>
    <%= f.label(:maybe, "I'll look into it.") %><br>
    <%= f.radio_button(:category, "0") %>
    <%= f.label(:meh, "I'm indifferent.") %><br>
    <%= f.radio_button(:category, "-1") %>
    <%= f.label(:no, "This is definitely not for me.") %><br>
    <!-- gets the id of the user currently being viewed so 
         that a recommendation can be created for that user -->
    <%= f.submit "Ok", class: "btn btn-primary" %>  
  <% end %>
</div>

app/views/recommendations/_recommendation.html.erb
<li id="recommendation-<%= recommendation.id %>">
  <p>
    <!--displays link to view each recommendation in a pop up window -->
    <h4><span id="rec-title-<%= recommendation.id %>"><%= link_to recommendation.title, recommendation_path(recommendation.id), :remote => true %></span></h4>
  </p>
</li>

app/views/recommendations/show.html.erb
<!-- ID necessary for the overlay on users#review -->
<div id="rec-<%= @recommendation.id %>-details" style="visibility: visible; width:100%; height:100%; position: absolute; z-index:1000; background:black; opacity:0.7; left:0px; top:0px;">
  <!-- Modal with recommendation info -->
  <div style="width:600px; background-color: #fff; border:1px solid #000; margin: 100px auto; padding:15px">
    Description: <%= @recommendation.description %><br>
    Type: <%= @recommendation.category %><br>
    Words that describe <%= @recommendation.title %><br>

    <div>
        <%= form_for(@recommendation) do |f| %>
        <%= f.label :feedback, "What do you think of this recommendation?" %><br><br>
        <%= f.radio_button(:feedback, "1") %>
        <%= f.label(:yes, "This is definitely for me.") %><br>
        <%= f.radio_button(:feedback, ".5") %>
        <%= f.label(:maybe, "I'll look into it.") %><br>
        <%= f.radio_button(:feedback, "0") %>
        <%= f.label(:meh, "I'm indifferent.") %><br>
        <%= f.radio_button(:feedback, "-1") %>
        <%= f.label(:no, "This is definitely not for me.") %><br>
        <%= f.submit "Ok", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/recommendations/show.js.erb
$(document).ready(function(){
  // once the recommendation title is clicked in app/views/users/review, the recommendation details will be shown
  $('#rec-title-<%=@recommendation.id %>').click(function() {

    el = document.getElementById('#rec-<%= @recommendation.id %>-details');
    //el.style.visibility = (el.style.visibility == "visibile") ? "hidden" : "visible";
    $('body').append('<%= escape_javascript(render :template => "recommendations/show.html.erb") %>');

  });
});