config/routes.rb
Rails.application.routes.draw do

  get       'sessions/new'

  root	    'static_pages#home'
  
  get       'nda_page'        =>  'users#nda_page'
  
  get       'signup_1'        =>  'users#new'
  
  post      'signup_2'        =>  'users#create'
  
  patch     'new_user_feed'	  =>  'users#augment'
  
  get       'feed'            =>  'users#index'
  
  get       'review'          =>  'users#review'

  get       'login'           => 'sessions#new'
  post      'login'           => 'sessions#create'
  
  delete    'logout'          => 'sessions#destroy'

  resources :users
  resources :recommendations

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recommendations, dependent: :destroy
  #Commented out to test fields_for
  has_and_belongs_to_many :books
  #has_many :books_users
  #has_many :books, :through => :books_users
  has_and_belongs_to_many :movies
  has_and_belongs_to_many :songs
  has_and_belongs_to_many :games
  has_and_belongs_to_many :foods
  has_and_belongs_to_many :destinations
  accepts_nested_attributes_for :books
  accepts_nested_attributes_for :movies
  accepts_nested_attributes_for :songs
  accepts_nested_attributes_for :games
  accepts_nested_attributes_for :foods
  accepts_nested_attributes_for :destinations

  before_save {self.username = username.downcase}
  before_save {self.email    = email.downcase}

  # Username is required and must be unique; not case sensitive
  validates :username, presence: true, uniqueness: {case_sensitive: false}, 
                       length: {maximum: 30} 
  # First and last name are required; maximum of 20 characters
  validates :firstName, presence: true, length: {maximum: 20}
  validates :lastName, presence: true, length: {maximum: 20}
  validates :birthday, presence: true
  # Password is required; still needs to be encrypted
  validates :password_digest, presence: true, length: {minimum: 8}

  # Email address is required and must be unique; not case sensitive; must follow correct format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
                    format: {with: VALID_EMAIL_REGEX }, 
                    uniqueness: {case_sensitive: false}

  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # checks to make sure there is a logged in user before loading the page and
  #performs certain actions if there isn't
  before_action :logged_in_user, only: [:augment, :recommendations, :index, 
                                        :review]
                                        
  # checks to make sure the user view the page is the user which should be
  #viewing (in the case of multiple windows, etc)|
  #this isn't behaving currently. Not immediately clear why.
  #before_action :correct_user, only: [:edit, :recommendations]
  
  # checks to make sure the user's nda_agree is "true", or it redirects to nda
  before_action :nda_signed, only: [:augment, :recommendations, :index, :review]
  
  #Action to display the NDA page. Called when "Sign Up" is clicked.
  def nda_page
    render "nda_page/nda_page"
    @@nda_agree = false
  end
  
  #Action to create a new user. Called when "I agree" is clicked on NDA page.
  def new
    @user =         User.new
    @books =        Book.all
    @movies =       Movie.all
    @songs =        Song.all
    @games =        Game.all
    @foods =        Food.all
    @destinations = Destination.all
    @@nda_agree = true
  end

  # Action to create the new user on the first signup page. Called when "Next" 
  #is clicked.
  def create
    @user = User.new(user_params)
    # Handle a successful save.
    if @user.save
      @user.update_attribute(:nda_agree, @@nda_agree)
      log_in @user
      @read_interest = @user.read_interest
      # Previously "signup2"
      render 'edit'
    else
      render 'new'
    end
    
  end
  
  # This method is called to augment newly created users with their interests.
  # (Previously "signup2")
  def augment
    @users = User.all
    @user = current_user
    if @user.update_attributes(user_params)
      flash[:success] = "Welcome to Telmi!"
      render 'index'
    else
      render 'nda_page'
      flash[:danger] = "Unable to create user. Please try again."
    end
  end

  # Action to create a list of all users stored to a session variable.
  def index
    @users = User.all
    @user = current_user
  end
  
  # finds a given user based on the passed-in parameter
  def show
    @user = User.find(params[:id])
    @recommendation = @user.recommendations.build if logged_in?
  end

  def review
    @user = current_user
    @recommendations = @user.recommendations #.paginate(page: params[:page])
  end

  private

    # Method which defines which items are required and which are permitted when 
    #passing info on a user.
    def user_params
      params.require(:user).permit(:username, :firstName, :lastName, :email,
					                         :birthday, :password, :password_confirmation, 
					                         :location, :nda_agree, :read_interest, 
					                         :watch_interest, :listen_interest, 
					                         :play_interest, :eat_interest, 
					                         :travel_interest, :other_interest, 
					                         :book_ids => [], :movie_ids => [], 
					                         :song_ids => [], :game_ids => [], 
					                         :food_ids => [], :destination_ids =>[])
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
    
    # Confirms the user has signed the NDA and redirects if they haven't.
    def nda_signed
      @user = current_user
      unless @user.nda_agree?
        flash[:danger] = "Please agree to NDA before proceeding"
        redirect_to nda_page_url
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def age(id)
    @now = Date.today
    @user = User.find(id)
     if @user.birthday.month < @now.month
       @user_age = @now.year - @user.birthday.year
         #print @user_age
     elsif @user.birthday.month == @now.month
       if @user.birthday.day <= @now.day
         @user_age = @now.year - @user.birthday.year
         #print @user_age
       end
     else
         @user_age = @now.year - @user.birthday.year - 1
         #print @user_age
     end

    #puts "here!"
  end
end

app/views/users/edit.html.erb
<h4 class="col-md-offset-2">Given the opportunity to experience anything in the
                            world, what would you be interested in receiving 
                            recommendations for?</h4>
<h4 class="col-md-offset-2">Check all that apply<h4>

<div class="row">
  <div class="col-md-6 col-md-offset-2">
    <%= form_for(@user, url: new_user_feed_path) do |f| %>
      
      <%= f.label :read_interest, "Things to read (books, magazines, 
                                 articles)" %>
      <%= f.check_box :read_interest, id: "read-interest-box" %><br>
      
      <%= f.label :watch_interest, "Things to watch (movies, shows, online 
                                 videos)" %>
      <%= f.check_box :watch_interest, id: "watch-interest-box" %><br>
      
      <%= f.label :listen_interest, "Things to listen to (music, audiobooks, 
                                 lectures)" %>
      <%= f.check_box :listen_interest, id: "listen-interest-box" %><br>
      
      <%= f.label :play_interest, "Things to play (video games, apps, 
                                 board games)" %>
      <%= f.check_box :play_interest, id: "play-interest-box" %><br>
      
      <%= f.label :eat_interest, "Things to eat (restaurants, cuisine, 
                                 store-bought)" %>
      <%= f.check_box :eat_interest, id: "eat-interest-box" %><br>
      
      <%= f.label :travel_interest, "Places to visit (venues, stores, historical, 
                                 vacation)" %>
      <%= f.check_box :travel_interest, id: "visit-interest-box" %><br>
      
      <%= f.label :other_interest, "Other:" %>
      <%= f.check_box :other_interest, id: "other-interest-box" %>
      <%= f.text_field :other_interest, id: "other-interest-text" %><br>

      <%= f.submit "Finish", class: "btn btn-primary" %>
      
    <% end %>
    
  </div>
</div>
<%= javascript_include_tag "application" %>

app/views/users/index.html.erb
<h1 class="col-md-offset-1">Feed</h1>
<h4 class="col-md-offset-1">Make recommendations to other users based on the 
                            information they've provided.</h4>

<ul class="users col-md-offset-1">
  <% @users.each do |user| %>
    <li>
      <p>
      <%= link_to user.username, user %><br>
      Age: <%= age(user.id) %><br>
      Location: <%= user.location %><br>
      
      <% interests = [] %>
      <% interests << "things to read"         if user.read_interest? %>
      <% interests << "things to watch"        if user.watch_interest? %>
      <% interests << "things to listen to"    if user.listen_interest? %>
      <% interests << "things to play"         if user.play_interest? %>
      <% interests << "things to eat"          if user.eat_interest? %>
      <% interests << "places to visit"        if user.travel_interest? %>
      <% interests << "#{user.other_interest}" if user.other_interest? %>
      
      Looking for: <%= interests.join(", ") %><br>
    </li>
  <% end %>
</ul>

<br><br><br>
<h4 class="col-md-offset-4"> That's it for now! Check back later for more. </h4>

app/views/users/new.html.erb
<h1 class="center">Sign Up</h1>

<div class="row", id="signup-one">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_2_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :firstName, "First Name" %><br>
      <%= f.text_field :firstName, class: "signup-one-field" %><br>

      <%= f.label :lastName, "Last Name" %><br>
      <%= f.text_field :lastName, class: "signup-one-field" %><br>

      <%= f.label :email %><br>
      <%= f.email_field :email, class: "signup-one-field" %><br>

      <%= f.label :username %><br>
      <%= f.text_field :username, class: "signup-one-field" %><br>

      <%= f.label :password %><br>
      <%= f.password_field :password, class: "signup-one-field" %><br>

      <%= f.label :password_confirmation, "Password Confirmation" %><br>
      <%= f.password_field :password_confirmation, class: "signup-one-field" %><br>
      
      <%= f.label :birthday, "Birthday" %><br>
      <%= f.date_field :birthday, 
                       #Delali, I took this out and the date picker works.
                       #:data => {:provide => "datepicker"},
	                     class: "datepicker-form", 
	                     :placeholder => "MM/DD/YYY" %><br>

      <%= f.label :location, "Location (Optional)" %><br>
      <%= f.text_field :location, class: "signup-one-field" %><br>

      <%= f.submit "Next", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/recommendations.html.erb
<h2 class="col-md-offset-1">Your Recommendations</h2>
<p class="col-md-offset-1">Click on an item below to see details.</p><br><br>

<div class="col-md-offset-1">
  <% if @user.recommendations.any? %>
    <ul class = "recommendations">
      <!-- displays contents of app/views/recommendations/_recommendation.html.erb -->
      <%= render @recommendations %>
    </ul>
  <% end %>
</div>

app/views/users/review.html.erb
<h2 class="col-md-offset-1">Your Recommendations</h2>
<p class="col-md-offset-1">Click on an item below to see details.</p><br><br>

<div class="col-md-offset-1">
  <% if @user.recommendations.any? %>
    <ul class = "recommendations">
      <!-- displays contents of app/views/recommendations/_recommendation.html.erb for each of the current user's recommendations -->
      <%= render @recommendations %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-offset-1">
  <p>Name: <%= @user.firstName %> <%= @user.lastName %></p>
  <p>Username: <%= @user.username %></p>
  <p>Location: <%= @user.location %></p><br>

  <% if @user.books.any? %>
    <h4>Things <%= @user.username %> likes to read: </h4>
      <ul class="things-to-read">
	<%= @user.books.map {|b| b.title}.join(', ') %>
      </ul>
  <% end %>

  <% if @user.movies.any? %>
    <h4>Things <%= @user.username %> likes to watch: </h4>
      <ul class="things-to-watch">
        <%= @user.movies.map {|m| m.title}.join(', ') %>
      </ul>
  <% end %>

  <% if @user.songs.any? %>
    <h4>Things <%= @user.username %> likes to listen to: </h4>
      <ul class="things-to-listen">
        <%= @user.songs.map {|s| s.title}.join(', ') %>
      </ul>
  <% end %>

  <% if @user.games.any? %>
    <h4>Things <%= @user.username %> likes to play: </h4>
      <ul class="things-to-play">
        <%= @user.games.map {|g| g.title}.join(', ') %>
      </ul>
  <% end %>

  <% if @user.foods.any? %>
    <h4>Foods (or places where) <%= @user.username %> likes to eat: </h4>
      <ul class="things-to-eat">
        <%= @user.foods.map {|f| f.title}.join(', ') %>
      </ul>
  <% end %>

  <% if @user.destinations.any? %>
    <h4>Places <%= @user.username %> likes to visit: </h4>
      <ul class="things-to-visit">
        <%= @user.destinations.map {|d| d.title}.join(', ') %>
      </ul>
  <% end %>

</div>

<button id="new-recommendation" class="btn btn-primary">New Recommendation</button>

<!-- removed if statement since users will have to be logged in to get to this page -->  
<div id="recommendation-form" class="col-md-offset-2">
  <%= render 'shared/recommendation_form' %>
</div>

<%= javascript_include_tag 'application' %>