config/routes.rb
Rails.application.routes.draw do

  get       'sessions/new'

  root	    'static_pages#home'
  
  get       'nda_page'        =>  'users#nda_page'
  
  get       'signup_1'        =>  'users#new'
  
  post      'signup_2'        =>  'users#create'
  
  patch     'new_user_feed'	  =>  'users#augment'
  
  get       'feed'            =>  'users#index'
  
  get       'review'          =>  'users#review'

  get       'login'           => 'sessions#new'
  post      'login'           => 'sessions#create'
  
  delete    'logout'          => 'sessions#destroy'

  resources :users
  resources :recommendations

end

app/models/book.rb
class Book < ActiveRecord::Base
  
  #Commented out for testing the fields_for method
  has_and_belongs_to_many :users
  #has_many :books_users
  #has_many :users, :through => :books_users
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :category, presence: true
  validates :description, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/things_to_read.rb
class ThingsToRead < ActiveRecord::Base
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recommendations, dependent: :destroy
  #Commented out to test fields_for
  has_and_belongs_to_many :books
  #has_many :books_users
  #has_many :books, :through => :books_users
  has_and_belongs_to_many :movies
  has_and_belongs_to_many :songs
  has_and_belongs_to_many :games
  has_and_belongs_to_many :foods
  has_and_belongs_to_many :destinations
  accepts_nested_attributes_for :books
  accepts_nested_attributes_for :movies
  accepts_nested_attributes_for :songs
  accepts_nested_attributes_for :games
  accepts_nested_attributes_for :foods
  accepts_nested_attributes_for :destinations

  before_save {self.username = username.downcase}
  before_save {self.email    = email.downcase}

  # Username is required and must be unique; not case sensitive
  validates :username, presence: true, uniqueness: {case_sensitive: false}, 
                       length: {maximum: 30} 
  # First and last name are required; maximum of 20 characters
  validates :firstName, presence: true, length: {maximum: 20}
  validates :lastName, presence: true, length: {maximum: 20}
  validates :birthday, presence: true
  # Password is required; still needs to be encrypted
  validates :password_digest, presence: true, length: {minimum: 8}

  # Email address is required and must be unique; not case sensitive; must follow correct format
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255}, 
                    format: {with: VALID_EMAIL_REGEX }, 
                    uniqueness: {case_sensitive: false}

  has_secure_password
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/nda_page_helper.rb
module NdaPageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  #Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  # Redirects to stored Location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end
  
  #Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def age(id)
    @now = Date.today
    @user = User.find(id)
     if @user.birthday.month < @now.month
       @user_age = @now.year - @user.birthday.year
         #print @user_age
     elsif @user.birthday.month == @now.month
       if @user.birthday.day <= @now.day
         @user_age = @now.year - @user.birthday.year
         #print @user_age
       end
     else
         @user_age = @now.year - @user.birthday.year - 1
         #print @user_age
     end

    #puts "here!"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="container">
    <%= link_to "TELMI", feed_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Feed", feed_path %></li>
          <li><%= link_to "Recommendations", review_path %></li>
	        <li class="divider"></li>
	        <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
	      <% else %>
	        <li><%= link_to "Sign Up", nda_page_path %></li>
	        <li><%= link_to "Log In", login_path %></li>
	      <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telmi.Life</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>

  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_recommendation_form.html.erb
<%= form_for(@recommendation) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.label :title, "What is the name of the thing you are recommending?" %><br>
    <%= f.text_area :title %><br><br>

    <%= f.label :category, "What is it?" %><br><br>
    <%= f.radio_button(:category, "read") %>
    <%= f.label(:cat_read, "Something to read") %><br>
    <%= f.radio_button(:category, "watch") %>
    <%= f.label(:cat_watch, "Something to watch") %><br>
    <%= f.radio_button(:category, "listen") %>
    <%= f.label(:cat_listen, "Something to listen to") %><br>
    <%= f.radio_button(:category, "play") %>
    <%= f.label(:cat_play, "Something to play") %><br>
    <%= f.radio_button(:category, "eat") %>
    <%= f.label(:cat_eat, "Something to eat") %><br>
    <%= f.radio_button(:category, "go") %>
    <%= f.label(:cat_go, "Somewhere to go") %><br><br>

    <%= f.label :description, "Provide a few sentences to describe the recommendation." %><br>
    <%= f.text_area :description %><br><br>

    <!-- gets the id of the user currently being viewed so 
         that a recommendation can be created for that user -->
    <%= f.hidden_field(:user_id, :value => @user.id) %>

  <%= f.submit "I'm Done", class: "btn btn-primary", id: "rec-form-submit" %>
  </div>
<% end %>